### ISSUE TITLE
Priorities 2022

### ISSUE THREAD

**Issue by Robinlovelace** [U-Shift/biclar#10]
Great to chat about these @temospena we can keep ideas updated here https://excalidraw.com/#room=39230e61f85e5853bb5e,AhRUYmQyP0JsWTk5p3lzGA

![image](https://user-images.githubusercontent.com/1825120/121500670-6df6b080-c9d6-11eb-8cb8-7af54576dfe9.png)

**Comment by temospena** [comment]
Things to do.
Maybe need some help on the order (and priority) of this:

- [ ] update existing cycling network at OSM (in progress)
- [ ] make sure that Cyclestreets is using the most up-tp-date OSM network for Metro Lisbon
- [ ] jittering for all trips, and select the best threshold
- [ ] batch routing, for balanced? fast? quiet?

**For ENMAC scenario**
- [ ] select the threshold for the distance and max slope of bicycle trips that are reasonable (?)
- [ ] select the max age / distance to use a conventional bike

**For multi-modal scenario**
- [ ] select the trips that are potentially replaced by multimodal
- [ ] Jittering from Origins to stations, and stations to Destinations (?)
- [ ] batch routing
- [ ] select the ratio bike/transit that makes sense (?)

**For e-bike scenario**
- [ ] select the threshold for the distance and max slope of bicycle trips that are reasonable with e-bike


**For visualization**
- [ ] get a server with R shiny
- [ ] Prepare for 3 scenarios

**For socio-economic benefits estimation**
...

**Comment by Robinlovelace** [comment]
This is a great priority list, thank you Rosa!

**Comment by temospena** [comment]
Regarding the
>  update existing cycling network at OSM (in progress)
>  make sure that Cyclestreets is using the most up-tp-date OSM network for Metro Lisbon

The existing cycling network was about 95% updated by 29th May.
CycleStreets will be updated with those changes in mid-june.
The 100% will only be available for batch routing in mid-july.

**Comment by temospena** [comment]
Some of the priorities make no longer sence, regarding the methods we opt to use in the end.

Closing this now, but looking forward to adapt some of the progress we made with biclar in atumworld 🪁
