### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by temospena** [U-Shift/biclar#14]
I'd like start organizing a kind of a github pages website to have the documentation on the used methods, so that I don't get lost and know what/how was done in the future.
Something todo.

**Comment by temospena** [comment]
We have a website and documentation! 🎉 
https://u-shift.github.io/biclar/

To create new articles (not the same as vignettes)
`usethis::use_article()`

**Comment by Robinlovelace** [comment]
Great to see! I think this issue is fixed :+1:
