### ISSUE TITLE
weights in jittering

### ISSUE THREAD

**Issue by temospena** [U-Shift/biclar#24]
One of the problems raised by one municipality was that apparently there were more trips connecting a low density neighborhood but with a lot of road network vertices, than connecting to a high density neighborhood with less vertices.
![image](https://user-images.githubusercontent.com/39107166/176479120-7c960570-0833-4690-9d28-e62454a58ed5.png)
![image](https://user-images.githubusercontent.com/39107166/176479697-c82167b6-ca56-48ff-bf0c-1e5d92a3d8f8.png)

Should we try to use other weights in jittering?

**Comment by Robinlovelace** [comment]
:+1:

**Comment by Robinlovelace** [comment]
Agreed. Trying to post this message with Ctrl+Enter again as a test...
