### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Robinlovelace** [U-Shift/biclar#30]
I've tried a few different ways but guess the quickest now may be to replace cols4all with another package, and remove kableExtra.

**Comment by temospena** [comment]
can we replace by the color palette itself?
mako and rocket comes from "viridis", blues comes from "brewer", and so on

**Comment by Robinlovelace** [comment]
Yes, we could do :+1:

**Comment by temospena** [comment]
cool!
we can wait to be on cran, then.

if we need meanwhile, I can try burglr, but then I'm not sure how to remove cols4all to dependencies and add to description.

**Comment by mtennekes** [comment]
You're welcome @Robinlovelace Glad that cols4all is already used :-) 
Happy to receive feedback at https://github.com/mtennekes/cols4all/issues/18

**Comment by temospena** [comment]
solved, after cols4all to be on CRAN

changed parameters at https://github.com/U-Shift/biclar/blob/master/.github/workflows/pkgdown.yaml
using `JamesIves/github-pages-deploy-action@v4.4.1`
