### ISSUE TITLE
health benefits

### ISSUE THREAD

**Issue by temospena** [U-Shift/biclar#31]
have a look at this method:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8463831/

**Comment by temospena** [comment]
and this, although doesn't seems easy to setup:

https://github.com/ITHIM/valencia_training

**Comment by temospena** [comment]
- [ ] make a table with all estimations I need to compute, including values of trips, average trip length for all modes (cycling and car in particular), and the general population trip.

**Comment by temospena** [comment]
running the [heat_prep.R](https://github.com/U-Shift/biclar/blob/master/code/test-code/heat-prep.R) for whole region, and [heat_prep_municipios.R](https://github.com/U-Shift/biclar/blob/master/code/test-code/heat-prep_municipios.R) for all the 18 municipalities.
Check if the sum of municipalities differ much from whole region estimates results.

**Comment by temospena** [comment]
For 2 different scenarios:

```r
# cenario 1-4-3
sum(HEAT_municipios_143$Mortality))) #11.889
sum(HEAT_municipios_143$CO2eq))) #7668
sum(HEAT_municipios_143$Economic) #37777970

sum(HEAT_AML_143$Mortality))) #12
sum(HEAT_AML_143$CO2eq))) #7658
sum(HEAT_AML_143$Economic) #37882000

#cenario 2-10-4
sum(HEAT_municipios_2104$Mortality))) #89.41
sum(HEAT_municipios_2104$CO2eq))) #65533
sum(HEAT_municipios_2104$Economic) #284019900

sum(HEAT_AML_2104$Mortality))) #90
sum(HEAT_AML_2104$CO2eq))) #65420
sum(HEAT_AML_2104$Economic) #284690000
```

We can consider that they are the same, so we can use the whole AML estimates and divide per cyclist/trip/lenght.

**Comment by Robinlovelace** [comment]
Great work on this Rosa!
