### ISSUE TITLE
redirect domain to landing page

### ISSUE THREAD

**Issue by temospena** [U-Shift/biclar#36]
Help needed to redirect
biclar.tmobilidade.pt -> https://u-shift.github.io/biclarwww/

I found some instructions to redirect a custom domain to an organization gh-pages but not for a specific repository.
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by temospena** [comment]
solved, with a fetching script of the biclarwww repo upon request.
it is now at [biclar.tmlmobilidade.pt](https://biclar.tmlmobilidade.pt)

**Comment by Robinlovelace** [comment]
Looking really good!
