### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Robinlovelace** [U-Shift/biclar#40]
I'm seeing this

![image](https://user-images.githubusercontent.com/1825120/234798473-dbfcc750-3492-454d-b2e4-fdce68ef4a61.png)

in https://u-shift.github.io/biclar/ any ideas?

**Comment by temospena** [comment]
Right. Tha is an iframe or html widget.
This website needs also a tidy up :)

You can use this one instead: [biclar.tmlmobilidade.pt ](https://biclar.tmlmobilidade.pt/)

**Comment by temospena** [comment]
> You can use this one instead: biclar.tmlmobilidade.pt 

which is the same as this one: https://u-shift.github.io/biclarwww/
