### ISSUE TITLE
Paper TRA

### ISSUE THREAD

**Issue by temospena** [U-Shift/biclar#42]
Include in the introduction some papers about bike + PT 

https://www.sciencedirect.com/science/article/pii/S096585640600111X
https://www.tandfonline.com/doi/full/10.1080/21650020.2014.955210
https://journals.sagepub.com/doi/abs/10.3141/2144-20
https://www.sciencedirect.com/science/article/pii/S136192099900019X

**Comment by temospena** [comment]
can't find papers about the Socio-environmental impacr estimates for first and last legs.

**Comment by Robinlovelace** [comment]
Had a look at these and think all the good ones are in there.
